<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\City;
use Illuminate\Database\Seeder;

class AreaSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $areas = ['Ascot',
        'Barbour Fields',
        'Barham Green',
        'Bellevue',
        'Belmont',
        'Belmont East',
        'Burnside',
        'City Centre',
        'Cowdray Park',
        'Donnington',
        'Queens Park East',
        'Emakhandeni',
        'Enqameni',
        'Enqotsheni',
        'Entumbane',
        'Fagadola',
        'Famona',
        'Forestvale',
        'Fortunes Gate',
        'Four Winds',
        'Glencoe',
        'Glengarry',
        'Glenville',
        'Granite Park',
        'Greengrove',
        'Greenhill',
        'Greenspan',
        'Gwabalanda',
        'Harrisvale',
        'Harrisville',
        'Highmount',
        'Hillcrest',
        'Hillside',
        'Hillside East',
        'Hillside South',
        'Hillside West',
        'Hume Park',
        'Hundred Acre Lots',
        'Hyde Park',
        'Hyde Park Estate',
        'Ianvale',
        'Ilanda',
        'Iminyela',
        'Intini',
        'Jacaranda',
        'Kelvin East',
        'Kelvin North',
        'Kelvin West',
        'Kenilworth',
        'Kilallo',
        'Killarney',
        'Kingsdale',
        'Kumalo',
        'Kumalo North',
        'Lakeside',
        'Lobengula',
        'Lobenvale',
        'Lockview',
        'Luveve',
        'Luveve',
        'Mabutweni',
        'Magwegwe',
        'Magwegwe North',
        'Magwegwe West',
        'Makokoba',
        'Malindela',
        'Manningdale',
        'Marlands',
        'Marvel',
        'Marvel A',
        'Matsheumhlope',
        'Matsheumhlope Lots',
        'Matshobana',
        'Montrose',
        'Morningside',
        'Mpopoma',
        'Mpopomo South',
        'Munda',
        'Mzilikazi',
        'Newmansford',
        'Newton',
        'Newton West',
        'Nguboyenja',
        'Njube',
        'Nketa 6',
        'Nketa 7',
        'Nketa 8',
        'Nketa 9',
        'Nkulumane 5',
        'Nkulumane 10',
        'Nkulumane 11',
        'Nkulumane 12',
        'Nkulumane 13',
        'Nkulumane 14',
        'Nkulumane 15',
        'North End',
        'North Lynne',
        'North Trenance',
        'North Trenance Estate',
        'Northgate',
        'Northlea',
        'Norwood Tracks',
        'Ntaba Moya',
        'Orange Grove',
        'PaddonhurstParklands',
        'Parkview',
        'Pelandaba',
        'Pumula',
        'Pumula South',
        'Pumula East',
        'Pumula North',
        'Queensdale',
        'Queens Park',
        'Raylton',
        'Richmond',
        'Richmond South',
        'Riverside',
        'Riverside North',
        'Riverside South',
        'Robert Sinyoka',
        'Romney Park',
        'Rowena',
        'Sauers Town',
        'Sauers Town West',
        'Sauers Township',
        'Sizinda',
        'Southdale',
        'Southwold',
        'Steeldale',
        'Suburbs',
        'Sunninghill',
        'Sunnyside',
        'Tegela',
        'Thorngrove',
        'Trenance',
        'Tshabalala',
        'Upper Glenville',
        'Valley Field',
        'Voullaire Extension',
        'Queens Park West',
        'Westgate',
        'Willsgrove',
        'Windsor Park',
        'Woodlands',
        'Woodville Park'];

        $city = City::create([
            'name'=>'Bulawayo'
        ]);

        foreach($areas as $area){
            Area::create([
                'name'=> $area,
                'city_id'=> $city->id
            ]);
        }
    }
}
